### ISSUE TITLE
do support multi-gpus?

### ISSUE THREAD

**Issue by LARRYMIN** [git-cloner/llama-lora-fine-tuning#1]
when try CUDA_VISIBLE_DEVICES=0,1  \
deepspeed fastchat/train/train_lora.py \ 
....

got 

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:0! (when checking argument for argument index in method

**Comment by little51** [comment]
If you have multiple GPUs, update fastchat/train/train_lora.py and using --num_gpus parameter,such as :
CUDA_VISIBLE_DEVICES=0,1 \
deepspeed --num_gpus=2 fastchat/train/train_lora.py \ 
  --deepspeed ./deepspeed-config.json \ 
  --lora_r 8 \ 
... ...

**Comment by LARRYMIN** [comment]
@little51  also got the same error after --num_gpus=2

**Comment by little51** [comment]
git pull,update fastchat/train/train_lora.py
