### ISSUE TITLE
3.3.3 Html to Markdown never finish.

### ISSUE THREAD

**Issue by ycat3** [git-cloner/llama-lora-fine-tuning#2]
Good work.

I followed instruction.
However, step 3.3.3
python3 fastchat/data/clean_sharegpt.py --in ./data/sg_90k.json --out ./data/sharegpt_clean.json

It's seems to never finish the job.
Ubuntu 22.04 with 64GB memory and RTX 3090 GPU.

**Comment by little51** [comment]
html to markdown,CPU computing is required, and the CPU requirements are high, otherwise it is very slow

**Comment by ycat3** [comment]
Thank you.

3.3.3 Html to Markdown
3.3.5 Split long conversations into short dialogues
These steps does not work on Ubuntu22.04 python 3.10.

I tried to use another PC, Ubuntu20.04 python 3.8.
It's works.
