### ISSUE TITLE
sequence length is longer than the specified maximum sequence length

### ISSUE THREAD

**Issue by ycat3** [git-cloner/llama-lora-fine-tuning#3]
I try to 13B model.
When fine-tuning , the following messages happens sometime.

Token indices sequence length is longer than the specified maximum sequence length for this model (762 > 512). Running this sequence through the model will result in indexing errors

Serious error, or negligible ?

**Comment by little51** [comment]
Just a warnning.https://github.com/huggingface/transformers/issues/1791
