### ISSUE TITLE
run   deepspeed fastchat/train/train_lora.py error

### ISSUE THREAD

**Issue by codezealot** [git-cloner/llama-lora-fine-tuning#4]
run   deepspeed fastchat/train/train_lora.py error, please help:

CUDA_VISIBLE_DEVICES=0 \
deepspeed fastchat/train/train_lora.py \
  --deepspeed ./deepspeed-config.json \
  --lora_r 8 \
  --lora_alpha 16 \
  --lora_dropout 0.05 \
  --model_name_or_path ./llama-7b-hf \
  --data_path ./data/sharegpt_clean_split.json \
  --fp16 True \
  --output_dir ./output \
  --num_train_epochs 1 \
  --per_device_train_batch_size 14 \
  --per_device_eval_batch_size 14 \
  --gradient_accumulation_steps 1 \
  --evaluation_strategy "no" \
  --save_strategy "steps" \
  --save_steps 2400 \
  --save_total_limit 5 \
  --learning_rate 2e-5 \
  --weight_decay 0. \
  --warmup_ratio 0.03 \
  --lr_scheduler_type "cosine" \
  --logging_steps 1 \
  --model_max_length 512 \
  --gradient_checkpointing True

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /root/autodl-tmp/llama-lora-fine-tuning/llama-lora-fine-tuning/fastchat/train/train_lora.py:165  │
│ in <module>                                                                                      │
│                                                                                                  │
│   162                                                                                            │
│   163 if __name__ == "__main__":                                                                 │
│   164 │   with torch.autocast("cuda"):                                                           │
│ ❱ 165 │   │   train()                                                                            │
│   166                                                                                            │
│                                                                                                  │
│ /root/autodl-tmp/llama-lora-fine-tuning/llama-lora-fine-tuning/fastchat/train/train_lora.py:136  │
│ in train                                                                                         │
│                                                                                                  │
│   133 │   )                                                                                      │
│   134 │   tokenizer.pad_token = tokenizer.unk_token                                              │
│   135 │   print("装载tokenizer")                                                                 │
│ ❱ 136 │   data_module = make_supervised_data_module(                                             │
│   137 │   │   tokenizer=tokenizer, data_args=data_args)                                          │
│   138 │   if torch.cuda.device_count() > 1:                                                      │
│   139 │   │   model.is_parallelizable = True                                                     │
│                                                                                                  │
│ /root/miniconda3/envs/llama-lora/lib/python3.10/site-packages/fastchat/train/train.py:228 in     │
│ make_supervised_data_module                                                                      │
│                                                                                                  │
│   225 │   eval_raw_data = [raw_data[i] for i in eval_indices]                                    │
│   226 │   rank0_print(f"#train {len(train_raw_data)}, #eval {len(eval_raw_data)}")               │
│   227 │                                                                                          │
│ ❱ 228 │   train_dataset = dataset_cls(train_raw_data, tokenizer=tokenizer)                       │
│   229 │   eval_dataset = dataset_cls(eval_raw_data, tokenizer=tokenizer)                         │
│   230 │   return dict(train_dataset=train_dataset, eval_dataset=eval_dataset)                    │
│   231                                                                                            │
│                                                                                                  │
│ /root/miniconda3/envs/llama-lora/lib/python3.10/site-packages/fastchat/train/train.py:162 in     │
│ __init__                                                                                         │
│                                                                                                  │
│   159 │   │                                                                                      │
│   160 │   │   rank0_print("Formatting inputs...")                                                │
│   161 │   │   sources = [example["conversations"] for example in raw_data]                       │
│ ❱ 162 │   │   data_dict = preprocess(sources, tokenizer)                                         │
│   163 │   │                                                                                      │
│   164 │   │   self.input_ids = data_dict["input_ids"]                                            │
│   165 │   │   self.labels = data_dict["labels"]                                                  │
│                                                                                                  │
│ /root/miniconda3/envs/llama-lora/lib/python3.10/site-packages/fastchat/train/train.py:99 in      │
│ preprocess                                                                                       │
│                                                                                                  │
│    96 │   │   conversations.append(conv.get_prompt())                                            │
│    97 │                                                                                          │
│    98 │   # Tokenize conversations                                                               │
│ ❱  99 │   input_ids = tokenizer(                                                                 │
│   100 │   │   conversations,                                                                     │
│   101 │   │   return_tensors="pt",                                                               │
│   102 │   │   padding="max_length",                                                              │
│                                                                                                  │
│ /root/miniconda3/envs/llama-lora/lib/python3.10/site-packages/transformers/tokenization_utils_ba │
│ se.py:2538 in __call__                                                                           │
│                                                                                                  │
│   2535 │   │   │   # input mode in this case.                                                    │
│   2536 │   │   │   if not self._in_target_context_manager:                                       │
│   2537 │   │   │   │   self._switch_to_input_mode()                                              │
│ ❱ 2538 │   │   │   encodings = self._call_one(text=text, text_pair=text_pair, **all_kwargs)      │
│   2539 │   │   if text_target is not None:                                                       │
│   2540 │   │   │   self._switch_to_target_mode()                                                 │
│   2541 │   │   │   target_encodings = self._call_one(text=text_target, text_pair=text_pair_targ  │
│                                                                                                  │
│ /root/miniconda3/envs/llama-lora/lib/python3.10/site-packages/transformers/tokenization_utils_ba │
│ se.py:2624 in _call_one                                                                          │
│                                                                                                  │
│   2621 │   │   │   │   │   f" {len(text_pair)}."                                                 │
│   2622 │   │   │   │   )                                                                         │
│   2623 │   │   │   batch_text_or_text_pairs = list(zip(text, text_pair)) if text_pair is not No  │
│ ❱ 2624 │   │   │   return self.batch_encode_plus(                                                │
│   2625 │   │   │   │   batch_text_or_text_pairs=batch_text_or_text_pairs,                        │
│   2626 │   │   │   │   add_special_tokens=add_special_tokens,                                    │
│   2627 │   │   │   │   padding=padding,                                                          │
│                                                                                                  │
│ /root/miniconda3/envs/llama-lora/lib/python3.10/site-packages/transformers/tokenization_utils_ba │
│ se.py:2806 in batch_encode_plus                                                                  │
│                                                                                                  │
│   2803 │   │   """                                                                               │
│   2804 │   │                                                                                     │
│   2805 │   │   # Backward compatibility for 'truncation_strategy', 'pad_to_max_length'           │
│ ❱ 2806 │   │   padding_strategy, truncation_strategy, max_length, kwargs = self._get_padding_tr  │
│   2807 │   │   │   padding=padding,                                                              │
│   2808 │   │   │   truncation=truncation,                                                        │
│   2809 │   │   │   max_length=max_length,                                                        │
│                                                                                                  │
│ /root/miniconda3/envs/llama-lora/lib/python3.10/site-packages/transformers/tokenization_utils_ba │
│ se.py:2443 in _get_padding_truncation_strategies                                                 │
│                                                                                                  │
│   2440 │   │                                                                                     │
│   2441 │   │   # Test if we have a padding token                                                 │
│   2442 │   │   if padding_strategy != PaddingStrategy.DO_NOT_PAD and (not self.pad_token or sel  │
│ ❱ 2443 │   │   │   raise ValueError(                                                             │
│   2444 │   │   │   │   "Asking to pad but the tokenizer does not have a padding token. "         │
│   2445 │   │   │   │   "Please select a token to use as `pad_token` `(tokenizer.pad_token = tok  │
│   2446 │   │   │   │   "or add a new pad token via `tokenizer.add_special_tokens({'pad_token':   │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ValueError: Asking to pad but the tokenizer does not have a padding token. Please select a token to use as `pad_token` `(tokenizer.pad_token = tokenizer.eos_token e.g.)`
or add a new pad token via `tokenizer.add_special_tokens({'pad_token': '[PAD]'})`.

**Comment by little51** [comment]
./llama-7b-hf exists ? the file's list like:
config.json
generation_config.json
pytorch_model-00001-of-00002.bin
pytorch_model-00002-of-00002.bin
pytorch_model.bin.index.json
special_tokens_map.json
tokenizer_config.json
tokenizer.json
tokenizer.model

**Comment by little51** [comment]
pip list | grep fschat,check version:
fschat     0.2.10 or Latest

**Comment by codezealot** [comment]
> 
Thank you! I suggest you add version numbers to all the packages in requirements.txt.

**Comment by little51** [comment]
ok,I modify requirements.txt

**Comment by cyrilakafia** [comment]
@codezealot did this work for you?
I am getting the same error
