### ISSUE TITLE
How to resume correct

### ISSUE THREAD

**Issue by ycat3** [git-cloner/llama-lora-fine-tuning#5]
I modified deepspeed-config.json file.
------------------------------------------------------------------------------
"activation_checkpointing": {
    "partition_activations": true,
    "contiguous_memory_optimization": true
  },
  "checkpoint": {
    "tag_validation": "Warn",
    "load_universal": false,
    "use_node_local_storage": true,
    "parallel_write":{
        "pipeline_stage": false
    }
  },
  "wall_clock_breakdown": false
----------------------------------------------------------------------
Resume works, however loss is pretty different before resume.

**Comment by little51** [comment]
Sorry, I haven't tried this method yet
