### ISSUE TITLE
down llama model so slowly

### ISSUE THREAD

**Issue by mz2sj** [git-cloner/llama-lora-fine-tuning#7]
hi~
I used llama.download to download model but the speed is so slow.Any advice for acceleration?
By the way,I used command `pip install pyllama -U` install pyllama.Is there any diffrence beween your suggesion command.
Thanks~

**Comment by little51** [comment]
There is no necessary to download LLAMA native model files and convert using convert_llama_weights_to_hf.py,please download llama huggingface format file direct:
git clone https://huggingface.co/decapoda-research/llama-7b-hf
download "lfs" files by browser,put these file together with llama-7b-hf

**Comment by mz2sj** [comment]
Thank you.I'll try this method!
